name: null
channels:
  - salilab
  - bioconda
  - r
  - conda-forge
  - defaults
  - schrodinger
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - aioeasywebdav=2.4.0=py37_1000
  - aiohttp=3.6.2=py37h516909a_0
  - altair=4.1.0=py_1
  - appdirs=1.4.3=py_1
  - async-timeout=3.0.1=py_1000
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py_0
  - bcrypt=3.1.7=py37h8f50634_1
  - bleach=3.1.5=pyh9f0ad1d_0
  - boto3=1.13.24=pyh9f0ad1d_0
  - botocore=1.16.24=pyh9f0ad1d_0
  - brotlipy=0.7.0=py37h8f50634_1000
  - bzip2=1.0.8=h516909a_2
  - ca-certificates=2020.4.5.2=hecda079_0
  - cachetools=4.1.0=py_1
  - cairo=1.16.0=h18b612c_1001
  - certifi=2020.4.5.2=py37hc8dfbb8_0
  - cffi=1.14.0=py37hd463f26_0
  - chardet=3.0.4=py37hc8dfbb8_1006
  - configargparse=1.2.3=pyh9f0ad1d_0
  - crc32c=2.0=py37h516909a_0
  - cryptography=2.9.2=py37hb09aad4_0
  - datrie=0.8.2=py37h8f50634_0
  - dbus=1.13.6=he372182_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - docutils=0.15.2=py37_0
  - dropbox=9.4.0=py_0
  - dssp=3.0.0=hf484d3e_3
  - entrypoints=0.3=py37hc8dfbb8_1001
  - expat=2.2.9=he1b5a44_2
  - fftw=3.3.8=nompi_h7f3a6c3_1110
  - filechunkio=1.8=py_2
  - fontconfig=2.13.1=he4413a7_1000
  - freetype=2.10.2=he06d7ca_0
  - ftputil=3.4=py_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - ghostscript=9.18=1
  - giflib=5.1.9=h516909a_0
  - git-lfs=2.11.0=0
  - gitdb=4.0.5=py_0
  - gitpython=3.1.3=py_0
  - glib=2.64.3=h6f030ca_0
  - google-api-core=1.17.0=py37hc8dfbb8_0
  - google-api-python-client=1.9.1=pyh9f0ad1d_0
  - google-auth=1.16.0=pyh9f0ad1d_0
  - google-auth-httplib2=0.0.3=py_3
  - google-cloud-core=1.3.0=py_0
  - google-cloud-storage=1.28.1=pyh9f0ad1d_0
  - google-resumable-media=0.5.1=pyh9f0ad1d_0
  - googleapis-common-protos=1.51.0=py37hc8dfbb8_2
  - graphite2=1.3.13=he1b5a44_1001
  - graphviz=2.38.0=hf68f40c_1011
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - harfbuzz=2.4.0=h37c48d4_1
  - httplib2=0.18.1=pyh9f0ad1d_0
  - icu=58.2=hf484d3e_1000
  - idna=2.9=py_1
  - imagemagick=7.0.8_11=pl526hc610aec_0
  - importlib-metadata=1.6.1=py37hc8dfbb8_0
  - importlib_metadata=1.6.1=0
  - ipykernel=5.3.0=py37h43977f1_0
  - ipython=7.15.0=py37hc8dfbb8_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=py_0
  - jbig=2.1=h516909a_2002
  - jedi=0.17.0=py37hc8dfbb8_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - jmespath=0.10.0=pyh9f0ad1d_0
  - jpeg=9d=h516909a_0
  - json5=0.9.0=py_0
  - jsonschema=3.2.0=py37hc8dfbb8_1
  - jupyter=1.0.0=py_2
  - jupyter_client=6.1.3=py_0
  - jupyter_console=6.1.0=py_1
  - jupyter_contrib_core=0.3.3=py_2
  - jupyter_contrib_nbextensions=0.5.1=py37_0
  - jupyter_core=4.6.3=py37hc8dfbb8_1
  - jupyter_highlight_selected_word=0.2.0=py37_1000
  - jupyter_latex_envs=1.4.6=py37_1000
  - jupyter_nbextensions_configurator=0.4.1=py37_0
  - jupyterlab=2.1.4=py_0
  - jupyterlab_server=1.1.5=py_0
  - ld_impl_linux-64=2.34=h53a641e_5
  - libblas=3.8.0=16_openblas
  - libboost=1.67.0=h46d08c1_4
  - libcblas=3.8.0=16_openblas
  - libffi=3.2.1=he1b5a44_1007
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libgfortran-ng=7.5.0=hdf63c60_6
  - libiconv=1.15=h516909a_1006
  - liblapack=3.8.0=16_openblas
  - libopenblas=0.3.9=h5ec1e0e_0
  - libpng=1.6.37=hed695b0_1
  - libprotobuf=3.12.3=h8b12597_0
  - libsodium=1.0.17=h516909a_0
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - libtiff=4.1.0=hc3755c2_3
  - libtool=2.4.6=h14c3975_1002
  - libuuid=2.32.1=h14c3975_1000
  - libwebp=0.5.2=7
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=h13577e0_2
  - libxslt=1.1.32=hae48121_1003
  - llvm-openmp=10.0.0=hc9558a2_0
  - lxml=4.4.1=py37h7ec2d77_0
  - lz4-c=1.9.2=he1b5a44_1
  - mafft=7.467=h516909a_0
  - markupsafe=1.1.1=py37h8f50634_1
  - minimap2=2.17=h8b12597_1
  - mistune=0.8.4=py37h8f50634_1001
  - multidict=4.7.5=py37h8f50634_1
  - nbconvert=5.6.1=py37hc8dfbb8_1
  - nbformat=5.0.6=py_0
  - ncbi-ngs-sdk=2.10.0=hdf6179e_0
  - ncurses=6.1=hf484d3e_1002
  - networkx=2.4=py_1
  - nodejs=12.4.0=he1b5a44_0
  - notebook=6.0.3=py37hc8dfbb8_0
  - numpy=1.18.5=py37h8960a57_0
  - oauth2client=4.1.3=py_0
  - openjpeg=2.3.1=h981e76c_3
  - openssl=1.1.1g=h516909a_0
  - packaging=20.4=pyh9f0ad1d_0
  - pandas=1.0.4=py37h0da4684_0
  - pandoc=2.9.2.1=0
  - pandocfilters=1.4.2=py_1
  - pango=1.40.14=he7ab937_1005
  - paramiko=2.7.1=py37_0
  - parso=0.7.0=pyh9f0ad1d_0
  - pbccs=4.2.0=1
  - pcre=8.44=he1b5a44_0
  - perl=5.26.2=h516909a_1006
  - perl-app-cpanminus=1.7044=pl526_1
  - perl-business-isbn=3.004=pl526_0
  - perl-business-isbn-data=20140910.003=pl526_0
  - perl-carp=1.38=pl526_3
  - perl-constant=1.33=pl526_1
  - perl-data-dumper=2.173=pl526_0
  - perl-encode=2.88=pl526_1
  - perl-exporter=5.72=pl526_1
  - perl-extutils-makemaker=7.36=pl526_1
  - perl-file-path=2.16=pl526_0
  - perl-file-temp=0.2304=pl526_2
  - perl-mime-base64=3.15=pl526_1
  - perl-parent=0.236=pl526_1
  - perl-uri=1.76=pl526_0
  - perl-xml-libxml=2.0132=pl526h7ec2d77_1
  - perl-xml-namespacesupport=1.12=pl526_0
  - perl-xml-sax=1.02=pl526_0
  - perl-xml-sax-base=1.09=pl526_0
  - perl-xsloader=0.24=pl526_0
  - pexpect=4.8.0=py37hc8dfbb8_1
  - pickleshare=0.7.5=py37hc8dfbb8_1001
  - pip=20.1.1=py_1
  - pixman=0.38.0=h516909a_1003
  - pkg-config=0.29.2=h516909a_1006
  - prettytable=0.7.2=py_3
  - prometheus_client=0.8.0=pyh9f0ad1d_0
  - prompt-toolkit=3.0.5=py_0
  - prompt_toolkit=3.0.5=0
  - protobuf=3.12.3=py37h3340039_0
  - psutil=5.7.0=py37h8f50634_1
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py_1001
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=py_0
  - pygments=2.6.1=py_0
  - pygraphviz=1.5=py37h8f50634_1002
  - pynacl=1.3.0=py37h516909a_1001
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.9.2=py37hcca6a23_4
  - pyrsistent=0.16.0=py37h8f50634_0
  - pysftp=0.2.9=py_1
  - pysocks=1.7.1=py37hc8dfbb8_1
  - python=3.7.6=cpython_h8356626_6
  - python-dateutil=2.8.1=py_0
  - python-irodsclient=0.8.2=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2020.1=pyh9f0ad1d_0
  - pyyaml=5.3.1=py37h8f50634_0
  - pyzmq=19.0.1=py37hac76be4_0
  - qt=5.9.7=h52cfd70_2
  - qtconsole=4.7.4=pyh9f0ad1d_0
  - qtpy=1.9.0=py_0
  - ratelimiter=1.2.0=py37_1000
  - raxml=8.2.12=h14c3975_1
  - readline=8.0=hf8c457e_0
  - requests=2.23.0=pyh8c360ce_2
  - rsa=4.0=py_0
  - s3transfer=0.3.3=py37hc8dfbb8_1
  - send2trash=1.5.0=py_0
  - setuptools=47.1.1=py37hc8dfbb8_0
  - simplejson=3.17.0=py37h8f50634_1
  - sip=4.19.8=py37hf484d3e_1000
  - six=1.15.0=pyh9f0ad1d_0
  - slacker=0.14.0=py_0
  - smmap=3.0.4=pyh9f0ad1d_0
  - snakemake=5.19.2=0
  - snakemake-minimal=5.19.2=py_0
  - sqlite=3.30.1=hcee41ef_0
  - sra-tools=2.10.0=pl526he1b5a44_0
  - terminado=0.8.3=py37hc8dfbb8_1
  - testpath=0.4.4=py_0
  - tk=8.6.10=hed695b0_0
  - toolz=0.10.0=py_0
  - toposort=1.5=py_3
  - tornado=6.0.4=py37h8f50634_1
  - traitlets=4.3.3=py37hc8dfbb8_1
  - uritemplate=3.0.1=py_0
  - urllib3=1.25.9=py_0
  - wcwidth=0.2.4=pyh9f0ad1d_0
  - webencodings=0.5.1=py_1
  - wheel=0.34.2=py_1
  - widgetsnbextension=3.5.1=py37_0
  - wrapt=1.12.1=py37h8f50634_1
  - xmlrunner=1.7.7=py_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxpm=3.5.13=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-libxt=1.1.5=h516909a_1003
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h516909a_0
  - yaml=0.2.5=h516909a_0
  - yarl=1.3.0=py37h516909a_1000
  - zeromq=4.3.2=he1b5a44_2
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.4=h6597ccf_3
  - pip:
    - alignparse==0.1.3
    - biopython==1.77
    - cycler==0.10.0
    - descartes==1.1.0
    - dill==0.3.1.1
    - dms-variants==0.6.0
    - dna-features-viewer==3.0.1
    - kiwisolver==1.2.0
    - logomaker==0.8
    - matplotlib==3.2.1
    - mizani==0.7.1
    - multiprocess==0.70.9
    - natsort==7.0.1
    - palettable==3.3.0
    - pathos==0.2.5
    - patsy==0.5.1
    - plotnine==0.6.0
    - pox==0.2.7
    - ppft==1.6.6.1
    - pysam==0.16.0
    - regex==2020.6.8
    - scipy==1.4.1
    - statsmodels==0.11.1
prefix: /fh/fast/bloom_j/computational_notebooks/jbloom/2020/SARS-CoV-2-RBD_DMS/env

